packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
  - "packages/tooling/*"
onlyBuiltDependencies:
  - bcrypt
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
  - "@nestjs/core"
  - "@scarf/scarf"
