packages:
  - apps/*
  - services/*
  - packages/*
  - packages/tooling/*

catalog:
  "@ai-sdk/anthropic": ^3.0.2
  "@ai-sdk/openai": ^3.0.2
  "@ai-sdk/react": ^3.0.6
  "@ai-sdk/ui-utils": ^1.2.11
  "@eslint/js": ^9.32.0
  "@nestjs/common": ^11.1.9
  "@nestjs/core": ^11.1.9
  "@nestjs/platform-express": ^11.1.9
  "@nestjs/swagger": ^8.0.0
  "@nestjs/testing": ^11.1.9
  "@playwright/test": ^1.48.0
  "@prisma/adapter-pg": ^7.2.0
  "@prisma/client": ^7.2.0
  "@tailwindcss/typography": ^0.5.16
  "@tanstack/query-core": ^5.83.0
  "@tanstack/query-persist-client-core": ^5.83.0
  "@tanstack/react-query": ^5.83.0
  "@tanstack/react-query-persist-client": ^5.83.0
  "@testcontainers/postgresql": ^10.8.3
  "@types/bcrypt": ^5.0.2
  "@types/express": ^5.0.6
  "@types/jsonwebtoken": ^9.0.5
  "@types/node": ^22.19.3
  "@types/pg": ^8.16.0
  "@types/react": ^18.3.23
  "@types/react-dom": ^18.3.7
  "@types/supertest": ^6.0.3
  "@vitejs/plugin-react-swc": ^3.11.0
  "@vitest/coverage-v8": ^2.1.4
  ai: ^6.0.6
  autoprefixer: ^10.4.21
  bullmq: ^5.25.1
  bcrypt: ^5.1.1
  class-validator: ^0.14.3
  date-fns: ^3.6.0
  date-fns-tz: ^3.2.0
  dotenv: ^17.2.3
  eslint: ^9.32.0
  execa: ^9.5.2
  globals: ^15.15.0
  husky: ^9.1.7
  jsonwebtoken: ^9.0.2
  lint-staged: ^15.2.10
  msw: ^2.6.6
  nanoid: ^5.1.6
  neverthrow: ^8.2.0
  pg: ^8.13.1
  postcss: ^8.5.6
  prettier: ^3.3.3
  prisma: ^7.2.0
  react: ^18.3.1
  react-dom: ^18.3.1
  reflect-metadata: ^0.2.2
  resend: ^6.6.0
  rxjs: ^7.8.2
  supertest: ^7.0.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  testcontainers: ^10.11.0
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  tsdown: ^0.18.0
  tsx: ^4.21.0
  typescript: ^5.9.3
  typescript-eslint: ^8.38.0
  vite: ^5.4.19
  vitest: ^2.1.4
  zod: ^3.25.76
  xstate: ^5.13.2

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/client"
  - "@prisma/engines"
  - "@scarf/scarf"
  - "@swc/core"
  - bcrypt
  - cpu-features
  - esbuild
  - msw
  - prisma
  - protobufjs
  - ssh2
