import { Module } from "@nestjs/common";
import { DataModule } from "@kerniflow/data";
import { KernelModule } from "../../shared/kernel/kernel.module";
import { SalesController } from "./adapters/http/sales.controller";
import { SalesApplication } from "./application/sales.application";
import { PrismaQuoteRepositoryAdapter } from "./infrastructure/adapters/prisma-quote-repository.adapter";
import { PrismaSalesOrderRepositoryAdapter } from "./infrastructure/adapters/prisma-order-repository.adapter";
import { PrismaSalesInvoiceRepositoryAdapter } from "./infrastructure/adapters/prisma-invoice-repository.adapter";
import { PrismaSalesPaymentRepositoryAdapter } from "./infrastructure/adapters/prisma-payment-repository.adapter";
import { PrismaSalesSettingsRepositoryAdapter } from "./infrastructure/adapters/prisma-settings-repository.adapter";
import { QUOTE_REPOSITORY_PORT } from "./application/ports/quote-repository.port";
import { SALES_ORDER_REPOSITORY_PORT } from "./application/ports/order-repository.port";
import { SALES_INVOICE_REPOSITORY_PORT } from "./application/ports/invoice-repository.port";
import { SALES_PAYMENT_REPOSITORY_PORT } from "./application/ports/payment-repository.port";
import { SALES_SETTINGS_REPOSITORY_PORT } from "./application/ports/settings-repository.port";
import { ID_GENERATOR_TOKEN } from "../../shared/ports/id-generator.port";
import { CLOCK_PORT_TOKEN } from "../../shared/ports/clock.port";
import { IDEMPOTENCY_STORAGE_PORT_TOKEN } from "../../shared/ports/idempotency-storage.port";
import { PartyModule } from "../party";
import { CUSTOMER_QUERY_PORT } from "../party/application/ports/customer-query.port";
import { AccountingModule } from "../accounting";
import { AccountingApplication } from "../accounting/application/accounting.application";
import { NestLoggerAdapter } from "../../shared/adapters/logger/nest-logger.adapter";
import {
  CreateQuoteUseCase,
  UpdateQuoteUseCase,
  SendQuoteUseCase,
  AcceptQuoteUseCase,
  RejectQuoteUseCase,
  ConvertQuoteToOrderUseCase,
  ConvertQuoteToInvoiceUseCase,
  GetQuoteUseCase,
  ListQuotesUseCase,
} from "./application/use-cases/quotes.usecases";
import {
  CreateSalesOrderUseCase,
  UpdateSalesOrderUseCase,
  ConfirmSalesOrderUseCase,
  FulfillSalesOrderUseCase,
  CancelSalesOrderUseCase,
  CreateInvoiceFromOrderUseCase,
  GetSalesOrderUseCase,
  ListSalesOrdersUseCase,
} from "./application/use-cases/orders.usecases";
import {
  CreateSalesInvoiceUseCase,
  UpdateSalesInvoiceUseCase,
  IssueSalesInvoiceUseCase,
  VoidSalesInvoiceUseCase,
  GetSalesInvoiceUseCase,
  ListSalesInvoicesUseCase,
} from "./application/use-cases/invoices.usecases";
import {
  RecordPaymentUseCase,
  ListPaymentsUseCase,
  ReversePaymentUseCase,
} from "./application/use-cases/payments.usecases";
import {
  GetSalesSettingsUseCase,
  UpdateSalesSettingsUseCase,
} from "./application/use-cases/settings.usecases";

@Module({
  imports: [DataModule, KernelModule, PartyModule, AccountingModule],
  controllers: [SalesController],
  providers: [
    PrismaQuoteRepositoryAdapter,
    PrismaSalesOrderRepositoryAdapter,
    PrismaSalesInvoiceRepositoryAdapter,
    PrismaSalesPaymentRepositoryAdapter,
    PrismaSalesSettingsRepositoryAdapter,

    { provide: QUOTE_REPOSITORY_PORT, useExisting: PrismaQuoteRepositoryAdapter },
    { provide: SALES_ORDER_REPOSITORY_PORT, useExisting: PrismaSalesOrderRepositoryAdapter },
    { provide: SALES_INVOICE_REPOSITORY_PORT, useExisting: PrismaSalesInvoiceRepositoryAdapter },
    { provide: SALES_PAYMENT_REPOSITORY_PORT, useExisting: PrismaSalesPaymentRepositoryAdapter },
    { provide: SALES_SETTINGS_REPOSITORY_PORT, useExisting: PrismaSalesSettingsRepositoryAdapter },

    {
      provide: CreateQuoteUseCase,
      useFactory: (
        quoteRepo: PrismaQuoteRepositoryAdapter,
        settingsRepo: PrismaSalesSettingsRepositoryAdapter,
        orderRepo: PrismaSalesOrderRepositoryAdapter,
        invoiceRepo: PrismaSalesInvoiceRepositoryAdapter,
        idGenerator: SystemIdGenerator,
        clock: SystemClock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new CreateQuoteUseCase({
          logger: new NestLoggerAdapter(),
          quoteRepo,
          settingsRepo,
          orderRepo,
          invoiceRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        QUOTE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: UpdateQuoteUseCase,
      useFactory: (
        quoteRepo: PrismaQuoteRepositoryAdapter,
        settingsRepo: PrismaSalesSettingsRepositoryAdapter,
        orderRepo: PrismaSalesOrderRepositoryAdapter,
        invoiceRepo: PrismaSalesInvoiceRepositoryAdapter,
        idGenerator: SystemIdGenerator,
        clock: SystemClock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new UpdateQuoteUseCase({
          logger: new NestLoggerAdapter(),
          quoteRepo,
          settingsRepo,
          orderRepo,
          invoiceRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        QUOTE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: SendQuoteUseCase,
      useFactory: (
        quoteRepo,
        settingsRepo,
        orderRepo,
        invoiceRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new SendQuoteUseCase({
          logger: new NestLoggerAdapter(),
          quoteRepo,
          settingsRepo,
          orderRepo,
          invoiceRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        QUOTE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: AcceptQuoteUseCase,
      useFactory: (
        quoteRepo,
        settingsRepo,
        orderRepo,
        invoiceRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new AcceptQuoteUseCase({
          logger: new NestLoggerAdapter(),
          quoteRepo,
          settingsRepo,
          orderRepo,
          invoiceRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        QUOTE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: RejectQuoteUseCase,
      useFactory: (
        quoteRepo,
        settingsRepo,
        orderRepo,
        invoiceRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new RejectQuoteUseCase({
          logger: new NestLoggerAdapter(),
          quoteRepo,
          settingsRepo,
          orderRepo,
          invoiceRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        QUOTE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: ConvertQuoteToOrderUseCase,
      useFactory: (
        quoteRepo,
        settingsRepo,
        orderRepo,
        invoiceRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new ConvertQuoteToOrderUseCase({
          logger: new NestLoggerAdapter(),
          quoteRepo,
          settingsRepo,
          orderRepo,
          invoiceRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        QUOTE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: ConvertQuoteToInvoiceUseCase,
      useFactory: (
        quoteRepo,
        settingsRepo,
        orderRepo,
        invoiceRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new ConvertQuoteToInvoiceUseCase({
          logger: new NestLoggerAdapter(),
          quoteRepo,
          settingsRepo,
          orderRepo,
          invoiceRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        QUOTE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: GetQuoteUseCase,
      useFactory: (
        quoteRepo,
        settingsRepo,
        orderRepo,
        invoiceRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new GetQuoteUseCase({
          logger: new NestLoggerAdapter(),
          quoteRepo,
          settingsRepo,
          orderRepo,
          invoiceRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        QUOTE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: ListQuotesUseCase,
      useFactory: (
        quoteRepo,
        settingsRepo,
        orderRepo,
        invoiceRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new ListQuotesUseCase({
          logger: new NestLoggerAdapter(),
          quoteRepo,
          settingsRepo,
          orderRepo,
          invoiceRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        QUOTE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },

    {
      provide: CreateSalesOrderUseCase,
      useFactory: (
        orderRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new CreateSalesOrderUseCase({
          logger: new NestLoggerAdapter(),
          orderRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: UpdateSalesOrderUseCase,
      useFactory: (
        orderRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new UpdateSalesOrderUseCase({
          logger: new NestLoggerAdapter(),
          orderRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: ConfirmSalesOrderUseCase,
      useFactory: (
        orderRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new ConfirmSalesOrderUseCase({
          logger: new NestLoggerAdapter(),
          orderRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: FulfillSalesOrderUseCase,
      useFactory: (
        orderRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new FulfillSalesOrderUseCase({
          logger: new NestLoggerAdapter(),
          orderRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: CancelSalesOrderUseCase,
      useFactory: (
        orderRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new CancelSalesOrderUseCase({
          logger: new NestLoggerAdapter(),
          orderRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: CreateInvoiceFromOrderUseCase,
      useFactory: (
        orderRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new CreateInvoiceFromOrderUseCase({
          logger: new NestLoggerAdapter(),
          orderRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: GetSalesOrderUseCase,
      useFactory: (
        orderRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new GetSalesOrderUseCase({
          logger: new NestLoggerAdapter(),
          orderRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: ListSalesOrdersUseCase,
      useFactory: (
        orderRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        audit
      ) =>
        new ListSalesOrdersUseCase({
          logger: new NestLoggerAdapter(),
          orderRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          audit,
        }),
      inject: [
        SALES_ORDER_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },

    {
      provide: CreateSalesInvoiceUseCase,
      useFactory: (
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        accounting,
        audit
      ) =>
        new CreateSalesInvoiceUseCase({
          logger: new NestLoggerAdapter(),
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          accounting,
          audit,
        }),
      inject: [
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AccountingApplication,
        AUDIT_PORT,
      ],
    },
    {
      provide: UpdateSalesInvoiceUseCase,
      useFactory: (
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        accounting,
        audit
      ) =>
        new UpdateSalesInvoiceUseCase({
          logger: new NestLoggerAdapter(),
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          accounting,
          audit,
        }),
      inject: [
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AccountingApplication,
        AUDIT_PORT,
      ],
    },
    {
      provide: IssueSalesInvoiceUseCase,
      useFactory: (
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        accounting,
        audit
      ) =>
        new IssueSalesInvoiceUseCase({
          logger: new NestLoggerAdapter(),
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          accounting,
          audit,
        }),
      inject: [
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AccountingApplication,
        AUDIT_PORT,
      ],
    },
    {
      provide: VoidSalesInvoiceUseCase,
      useFactory: (
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        accounting,
        audit
      ) =>
        new VoidSalesInvoiceUseCase({
          logger: new NestLoggerAdapter(),
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          accounting,
          audit,
        }),
      inject: [
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AccountingApplication,
        AUDIT_PORT,
      ],
    },
    {
      provide: GetSalesInvoiceUseCase,
      useFactory: (
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        accounting,
        audit
      ) =>
        new GetSalesInvoiceUseCase({
          logger: new NestLoggerAdapter(),
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          accounting,
          audit,
        }),
      inject: [
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AccountingApplication,
        AUDIT_PORT,
      ],
    },
    {
      provide: ListSalesInvoicesUseCase,
      useFactory: (
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        customerQuery,
        idempotency,
        accounting,
        audit
      ) =>
        new ListSalesInvoicesUseCase({
          logger: new NestLoggerAdapter(),
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          customerQuery,
          idempotency,
          accounting,
          audit,
        }),
      inject: [
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        CUSTOMER_QUERY_PORT,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AccountingApplication,
        AUDIT_PORT,
      ],
    },

    {
      provide: RecordPaymentUseCase,
      useFactory: (
        paymentRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        idempotency,
        accounting,
        audit
      ) =>
        new RecordPaymentUseCase({
          logger: new NestLoggerAdapter(),
          paymentRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          idempotency,
          accounting,
          audit,
        }),
      inject: [
        SALES_PAYMENT_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AccountingApplication,
        AUDIT_PORT,
      ],
    },
    {
      provide: ListPaymentsUseCase,
      useFactory: (
        paymentRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        idempotency,
        accounting,
        audit
      ) =>
        new ListPaymentsUseCase({
          logger: new NestLoggerAdapter(),
          paymentRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          idempotency,
          accounting,
          audit,
        }),
      inject: [
        SALES_PAYMENT_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AccountingApplication,
        AUDIT_PORT,
      ],
    },
    {
      provide: ReversePaymentUseCase,
      useFactory: (
        paymentRepo,
        invoiceRepo,
        settingsRepo,
        idGenerator,
        clock,
        idempotency,
        accounting,
        audit
      ) =>
        new ReversePaymentUseCase({
          logger: new NestLoggerAdapter(),
          paymentRepo,
          invoiceRepo,
          settingsRepo,
          idGenerator,
          clock,
          idempotency,
          accounting,
          audit,
        }),
      inject: [
        SALES_PAYMENT_REPOSITORY_PORT,
        SALES_INVOICE_REPOSITORY_PORT,
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AccountingApplication,
        AUDIT_PORT,
      ],
    },

    {
      provide: GetSalesSettingsUseCase,
      useFactory: (settingsRepo, idGenerator, clock, idempotency, audit) =>
        new GetSalesSettingsUseCase({
          logger: new NestLoggerAdapter(),
          settingsRepo,
          idGenerator,
          clock,
          idempotency,
          audit,
        }),
      inject: [
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },
    {
      provide: UpdateSalesSettingsUseCase,
      useFactory: (settingsRepo, idGenerator, clock, idempotency, audit) =>
        new UpdateSalesSettingsUseCase({
          logger: new NestLoggerAdapter(),
          settingsRepo,
          idGenerator,
          clock,
          idempotency,
          audit,
        }),
      inject: [
        SALES_SETTINGS_REPOSITORY_PORT,
        ID_GENERATOR_TOKEN,
        CLOCK_PORT_TOKEN,
        IDEMPOTENCY_STORAGE_PORT_TOKEN,
        AUDIT_PORT,
      ],
    },

    {
      provide: SalesApplication,
      useFactory: (
        createQuote,
        updateQuote,
        sendQuote,
        acceptQuote,
        rejectQuote,
        convertQuoteToOrder,
        convertQuoteToInvoice,
        getQuote,
        listQuotes,
        createOrder,
        updateOrder,
        confirmOrder,
        fulfillOrder,
        cancelOrder,
        createInvoiceFromOrder,
        getOrder,
        listOrders,
        createInvoice,
        updateInvoice,
        issueInvoice,
        voidInvoice,
        getInvoice,
        listInvoices,
        recordPayment,
        listPayments,
        reversePayment,
        getSettings,
        updateSettings
      ) =>
        new SalesApplication(
          createQuote,
          updateQuote,
          sendQuote,
          acceptQuote,
          rejectQuote,
          convertQuoteToOrder,
          convertQuoteToInvoice,
          getQuote,
          listQuotes,
          createOrder,
          updateOrder,
          confirmOrder,
          fulfillOrder,
          cancelOrder,
          createInvoiceFromOrder,
          getOrder,
          listOrders,
          createInvoice,
          updateInvoice,
          issueInvoice,
          voidInvoice,
          getInvoice,
          listInvoices,
          recordPayment,
          listPayments,
          reversePayment,
          getSettings,
          updateSettings
        ),
      inject: [
        CreateQuoteUseCase,
        UpdateQuoteUseCase,
        SendQuoteUseCase,
        AcceptQuoteUseCase,
        RejectQuoteUseCase,
        ConvertQuoteToOrderUseCase,
        ConvertQuoteToInvoiceUseCase,
        GetQuoteUseCase,
        ListQuotesUseCase,
        CreateSalesOrderUseCase,
        UpdateSalesOrderUseCase,
        ConfirmSalesOrderUseCase,
        FulfillSalesOrderUseCase,
        CancelSalesOrderUseCase,
        CreateInvoiceFromOrderUseCase,
        GetSalesOrderUseCase,
        ListSalesOrdersUseCase,
        CreateSalesInvoiceUseCase,
        UpdateSalesInvoiceUseCase,
        IssueSalesInvoiceUseCase,
        VoidSalesInvoiceUseCase,
        GetSalesInvoiceUseCase,
        ListSalesInvoicesUseCase,
        RecordPaymentUseCase,
        ListPaymentsUseCase,
        ReversePaymentUseCase,
        GetSalesSettingsUseCase,
        UpdateSalesSettingsUseCase,
      ],
    },
  ],
  exports: [SalesApplication],
})
export class SalesModule {}
