import { expect, type Page, type TestInfo } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { formatInTimeZone } from "date-fns-tz";
import Stripe from "stripe";
import { test } from "./fixtures.ts";
import { apiClient } from "../utils/api.ts";
import type { CoachingOfferDto, InvoiceDto } from "@corely/contracts";
import { signFakeStripeWebhook } from "./helpers/billing-fixtures.ts";
import { buildAuthHeaders, loginAsSeededUser } from "./helpers/auth.ts";

const API_URL = process.env.API_URL ?? "http://localhost:3000";
const SCREENSHOT_STAMP = new Date().toISOString().replace(/[:.]/g, "-");
const E2E_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

type SourceInvoiceLookup = {
  invoiceId: string;
  number: string | null;
  status: string;
  currency: string;
  sourceType: string | null;
  sourceId: string | null;
  paymentCount: number;
  deliveryCount: number;
};

type InvoiceDelivery = {
  invoiceId: string;
  to: string;
  status: string;
  provider: string;
  providerMessageId: string | null;
  lastError: string | null;
};

function uniqueSuffix() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function screenshotDirFor(testInfo: TestInfo): string {
  const dir = join(
    E2E_ROOT,
    "output",
    "coaching-invoice-after-payment-e2e",
    SCREENSHOT_STAMP,
    testInfo.project.name,
    slugify(testInfo.title)
  );
  mkdirSync(dir, { recursive: true });
  return dir;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

async function captureState(
  page: Page,
  testInfo: TestInfo,
  screenshotDir: string,
  name: string,
  title: string,
  payload: unknown
) {
  const formatted = escapeHtml(JSON.stringify(payload, null, 2));
  await page.setContent(
    `<!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>${escapeHtml(title)}</title>
        <style>
          body {
            margin: 0;
            background: linear-gradient(180deg, #ecfeff 0%, #dbeafe 100%);
            color: #0f172a;
            font-family: "IBM Plex Sans", sans-serif;
          }
          main { padding: 32px; }
          h1 { margin: 0 0 12px; font-size: 28px; }
          p { margin: 0 0 18px; color: #334155; }
          pre {
            margin: 0;
            padding: 20px;
            border-radius: 16px;
            background: #020617;
            color: #e2e8f0;
            font: 13px/1.5 "SFMono-Regular", monospace;
            white-space: pre-wrap;
            word-break: break-word;
          }
        </style>
      </head>
      <body>
        <main>
          <h1>${escapeHtml(title)}</h1>
          <p>Generated by the coaching invoice after payment e2e flow.</p>
          <pre>${formatted}</pre>
        </main>
      </body>
    </html>`
  );
  await page.setViewportSize({ width: 1440, height: 1200 });
  const path = join(screenshotDir, `${name}.png`);
  await page.screenshot({ path, fullPage: true });
  await testInfo.attach(name, { path, contentType: "image/png" });
}

function nextLocalWeekday(targetDay: number, timezone: string, minDaysAhead = 7): string {
  const cursor = new Date(Date.now() + minDaysAhead * 24 * 60 * 60 * 1000);
  for (let attempts = 0; attempts < 21; attempts += 1) {
    const weekday = Number(formatInTimeZone(cursor, timezone, "i")) % 7;
    if (weekday === targetDay) {
      return formatInTimeZone(cursor, timezone, "yyyy-MM-dd");
    }
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  throw new Error("Could not resolve a future local weekday");
}

function plusLocalDays(localDate: string, days: number): string {
  const cursor = new Date(`${localDate}T00:00:00.000Z`);
  cursor.setUTCDate(cursor.getUTCDate() + days);
  return cursor.toISOString().slice(0, 10);
}

async function createOffer(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  timezone: string,
  suffix: string
): Promise<CoachingOfferDto> {
  const response = await request.post(`${API_URL}/coaching-offers`, {
    headers: auth,
    data: {
      title: { en: `Invoice Coaching ${suffix}` },
      description: { en: "E2E invoice after payment coverage" },
      currency: "EUR",
      priceCents: 24000,
      sessionDurationMinutes: 60,
      meetingType: "video",
      availabilityRule: {
        timezone,
        weeklySlots: [{ dayOfWeek: 1, startTime: "09:00", endTime: "12:00" }],
        blackouts: [],
      },
      bookingRules: {
        minNoticeHours: 1,
        maxAdvanceDays: 30,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 0,
      },
      contractRequired: false,
      paymentRequired: true,
      localeDefault: "en",
      contractTemplate: null,
      prepFormTemplate: null,
      debriefTemplate: null,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  const body = (await response.json()) as { offer?: CoachingOfferDto };
  if (!body.offer) {
    throw new Error("Offer creation did not return offer");
  }
  return body.offer;
}

async function getAvailability(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  params: { from: string; to: string; timezone: string }
) {
  const response = await request.get(`${API_URL}/coaching/public/offers/${offerId}/availability`, {
    params,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    slots: Array<{
      startAt: string;
      endAt: string;
      displayStart: string;
      displayEnd: string;
    }>;
  };
}

async function createHold(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  slot: { startAt: string; endAt: string },
  name: string,
  email: string
) {
  const response = await request.post(`${API_URL}/coaching/public/offers/${offerId}/holds`, {
    data: {
      startAt: slot.startAt,
      endAt: slot.endAt,
      bookedByName: name,
      bookedByEmail: email,
      ttlSeconds: 600,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    hold: { id: string; expiresAt: string };
  };
}

async function startBooking(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  holdId: string,
  name: string,
  email: string
) {
  const response = await request.post(`${API_URL}/coaching/public/offers/${offerId}/bookings`, {
    data: {
      holdId,
      locale: "en",
      client: {
        displayName: name,
        email,
      },
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    engagement: { id: string; status: string; paymentStatus: string; invoiceId?: string | null };
    payment: { id: string; amountCents: number; providerCheckoutSessionId: string | null };
    session: { id: string };
    checkoutUrl: string;
  };
}

async function postStripeWebhook(
  request: import("@playwright/test").APIRequestContext,
  event: Record<string, unknown>
) {
  const rawBody = JSON.stringify(event);
  const fakeSignature = signFakeStripeWebhook(rawBody, "test-coaching-webhook-secret");
  let response = await request.post(`${API_URL}/coaching-engagements/webhooks/stripe`, {
    headers: {
      "Content-Type": "application/json",
      "stripe-signature": fakeSignature,
    },
    data: rawBody,
  });
  if (response.ok()) {
    return;
  }

  const stripeSecret =
    process.env.STRIPE_WEBHOOK_SECRET ??
    "whsec_cd7d117e34d198633d3c215ce9321c687c821577f783047cff8ecf25f0edeee5";
  const stripeSignature = Stripe.webhooks.generateTestHeaderString({
    payload: rawBody,
    secret: stripeSecret,
  });
  response = await request.post(`${API_URL}/coaching-engagements/webhooks/stripe`, {
    headers: {
      "Content-Type": "application/json",
      "stripe-signature": stripeSignature,
    },
    data: rawBody,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
}

async function getInvoice(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  invoiceId: string
) {
  const response = await request.get(`${API_URL}/invoices/${invoiceId}`, {
    headers: auth,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as { invoice: InvoiceDto };
}

async function waitForInvoicesBySource(
  tenantId: string,
  sourceId: string,
  expectedCount: number
): Promise<SourceInvoiceLookup[]> {
  const deadline = Date.now() + 60_000;
  while (Date.now() < deadline) {
    await apiClient.post("/test/drain-outbox");
    const body = await apiClient.post<{ invoices: SourceInvoiceLookup[] }>(
      "/test/invoices/by-source",
      {
        tenantId,
        sourceType: "coaching_engagement",
        sourceId,
      }
    );
    if (body.invoices.length >= expectedCount) {
      return body.invoices;
    }
    await new Promise((resolve) => setTimeout(resolve, 1_000));
  }
  throw new Error("Timed out waiting for coaching invoice");
}

async function waitForInvoiceDeliveries(
  tenantId: string,
  invoiceId: string,
  expectedCount: number
): Promise<InvoiceDelivery[]> {
  const deadline = Date.now() + 90_000;
  while (Date.now() < deadline) {
    await apiClient.post("/test/drain-outbox");
    const body = await apiClient.post<{ deliveries: InvoiceDelivery[] }>(
      "/test/invoices/email-deliveries",
      {
        tenantId,
        invoiceIds: [invoiceId],
      }
    );
    if (
      body.deliveries.length >= expectedCount &&
      body.deliveries[0] &&
      body.deliveries[0].status === "SENT" &&
      body.deliveries[0].providerMessageId
    ) {
      return body.deliveries;
    }
    await new Promise((resolve) => setTimeout(resolve, 1_000));
  }
  throw new Error("Timed out waiting for invoice email delivery");
}

async function waitForInvoicePdf(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  invoiceId: string
) {
  const deadline = Date.now() + 60_000;
  while (Date.now() < deadline) {
    await apiClient.post("/test/drain-outbox");
    const response = await request.get(`${API_URL}/invoices/${invoiceId}/pdf`, {
      headers: auth,
      params: { waitMs: "0" },
    });
    expect([200, 202].includes(response.status()), await response.text()).toBeTruthy();
    const body = (await response.json()) as {
      status: "PENDING" | "READY" | "FAILED";
      documentId?: string;
      downloadUrl?: string;
      errorMessage?: string;
    };
    if (body.status === "READY") {
      return body;
    }
    if (body.status === "FAILED") {
      throw new Error(body.errorMessage ?? "Invoice PDF generation failed");
    }
    await new Promise((resolve) => setTimeout(resolve, 1_000));
  }
  throw new Error("Timed out waiting for invoice PDF");
}

test.describe("Coaching invoice after payment", () => {
  test("generates one invoice, includes correct billing details, sends email, and resends without duplicate accounting rows", async ({
    page,
    request,
    testData,
  }, testInfo) => {
    const screenshotDir = screenshotDirFor(testInfo);
    const auth = buildAuthHeaders(await loginAsSeededUser(request, testData));
    const suffix = uniqueSuffix();
    const timezone = "Europe/Berlin";
    const clientName = `Invoice Client ${suffix}`;
    const clientEmail = `delivered+coaching-invoice-${suffix}@resend.dev`;

    const offer = await createOffer(request, auth, timezone, suffix);
    const localStartDate = nextLocalWeekday(1, timezone);
    const localEndDate = plusLocalDays(localStartDate, 1);
    const availability = await getAvailability(request, offer.id, {
      from: `${localStartDate}T00:00:00.000Z`,
      to: `${localEndDate}T23:59:59.999Z`,
      timezone,
    });
    const slot = availability.slots[0];
    expect(slot).toBeTruthy();

    const hold = await createHold(request, offer.id, slot, clientName, clientEmail);
    const booking = await startBooking(request, offer.id, hold.hold.id, clientName, clientEmail);

    await captureState(page, testInfo, screenshotDir, "01-booking-started", "Booking started", {
      offerId: offer.id,
      engagementId: booking.engagement.id,
      paymentId: booking.payment.id,
      sessionId: booking.session.id,
      checkoutUrl: booking.checkoutUrl,
    });

    await postStripeWebhook(request, {
      id: `evt_invoice_capture_${suffix}`,
      type: "checkout.session.completed",
      data: {
        object: {
          id: booking.payment.providerCheckoutSessionId,
          metadata: {
            tenantId: testData.tenant.id,
            engagementId: booking.engagement.id,
            paymentId: booking.payment.id,
          },
          payment_intent: `pi_invoice_${suffix}`,
          payment_status: "paid",
        },
      },
    });

    const invoicesBySource = await waitForInvoicesBySource(
      testData.workspace.id,
      booking.engagement.id,
      1
    );
    expect(invoicesBySource).toHaveLength(1);
    expect(invoicesBySource[0]?.paymentCount).toBe(1);

    const invoiceId = invoicesBySource[0]!.invoiceId;
    const invoiceResponse = await getInvoice(request, auth, invoiceId);
    const invoice = invoiceResponse.invoice;
    expect(invoice.sourceType).toBe("coaching_engagement");
    expect(invoice.sourceId).toBe(booking.engagement.id);
    expect(invoice.currency).toBe("EUR");
    expect(invoice.billToName).toBe(clientName);
    expect(invoice.billToEmail).toBe(clientEmail);
    expect(invoice.lineItems).toHaveLength(1);
    expect(invoice.lineItems[0]?.unitPriceCents).toBe(offer.priceCents);
    expect(invoice.totals.subtotalCents).toBe(offer.priceCents);
    expect(invoice.totals.taxCents).toBe(
      typeof invoice.taxSnapshot?.taxTotalAmountCents === "number"
        ? invoice.taxSnapshot.taxTotalAmountCents
        : 0
    );

    const pdf = await waitForInvoicePdf(request, auth, invoiceId);
    await captureState(page, testInfo, screenshotDir, "02-invoice-generated", "Invoice generated", {
      invoiceSummary: invoicesBySource[0],
      invoice,
      pdf,
    });

    const initialDeliveries = await waitForInvoiceDeliveries(testData.workspace.id, invoiceId, 1);
    expect(initialDeliveries).toHaveLength(1);
    await captureState(
      page,
      testInfo,
      screenshotDir,
      "03-email-sent",
      "Initial invoice email sent",
      {
        invoiceId,
        deliveries: initialDeliveries,
      }
    );

    const resendResponse = await request.post(
      `${API_URL}/coaching-engagements/${booking.engagement.id}/invoice/resend`,
      {
        headers: auth,
        data: {},
      }
    );
    expect(resendResponse.ok(), await resendResponse.text()).toBeTruthy();
    const resent = (await resendResponse.json()) as {
      invoiceId: string;
      deliveryId: string;
      status: string;
      to: string;
    };
    expect(resent.invoiceId).toBe(invoiceId);
    expect(resent.to).toBe(clientEmail);

    const deliveriesAfterResend = await waitForInvoiceDeliveries(
      testData.workspace.id,
      invoiceId,
      2
    );
    const invoicesAfterResend = await waitForInvoicesBySource(
      testData.workspace.id,
      booking.engagement.id,
      1
    );
    expect(invoicesAfterResend).toHaveLength(1);
    expect(invoicesAfterResend[0]?.paymentCount).toBe(1);
    expect(invoicesAfterResend[0]?.deliveryCount).toBe(2);

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "04-resend-without-duplicates",
      "Invoice resent without duplicate accounting rows",
      {
        resent,
        invoicesAfterResend,
        deliveriesAfterResend,
      }
    );
  });
});
