import { expect, type Page, type TestInfo } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { formatInTimeZone, fromZonedTime } from "date-fns-tz";
import { test } from "./fixtures.ts";
import type { CoachingOfferDto } from "@corely/contracts";
import { buildAuthHeaders, loginAsSeededUser } from "./helpers/auth.ts";
import { apiClient } from "../utils/api.ts";

const API_URL = process.env.API_URL ?? "http://localhost:3000";
const SCREENSHOT_STAMP = new Date().toISOString().replace(/[:.]/g, "-");
const E2E_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

function uniqueSuffix() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function screenshotDirFor(testInfo: TestInfo): string {
  const dir = join(
    E2E_ROOT,
    "output",
    "coaching-prep-questionnaire-e2e",
    SCREENSHOT_STAMP,
    testInfo.project.name,
    slugify(testInfo.title)
  );
  mkdirSync(dir, { recursive: true });
  return dir;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

async function captureState(
  page: Page,
  testInfo: TestInfo,
  screenshotDir: string,
  name: string,
  title: string,
  payload: unknown
) {
  const formatted = escapeHtml(JSON.stringify(payload, null, 2));
  await page.setContent(
    `<!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>${escapeHtml(title)}</title>
        <style>
          body {
            margin: 0;
            background: linear-gradient(180deg, #eff6ff 0%, #dbeafe 100%);
            color: #172554;
            font-family: "IBM Plex Sans", sans-serif;
          }
          main { padding: 32px; }
          h1 { margin: 0 0 12px; font-size: 28px; }
          p { margin: 0 0 18px; color: #1d4ed8; }
          pre {
            margin: 0;
            padding: 20px;
            border-radius: 16px;
            background: #0f172a;
            color: #dbeafe;
            font: 13px/1.5 "SFMono-Regular", monospace;
            white-space: pre-wrap;
            word-break: break-word;
          }
        </style>
      </head>
      <body>
        <main>
          <h1>${escapeHtml(title)}</h1>
          <p>Generated by the coaching prep questionnaire e2e flow.</p>
          <pre>${formatted}</pre>
        </main>
      </body>
    </html>`
  );
  await page.setViewportSize({ width: 1440, height: 1200 });
  const path = join(screenshotDir, `${name}.png`);
  await page.screenshot({ path, fullPage: true });
  await testInfo.attach(name, { path, contentType: "image/png" });
}

function nextLocalWeekday(targetDay: number, timezone: string, minDaysAhead = 7): string {
  const cursor = new Date(Date.now() + minDaysAhead * 24 * 60 * 60 * 1000);
  for (let attempts = 0; attempts < 21; attempts += 1) {
    const weekday = Number(formatInTimeZone(cursor, timezone, "i")) % 7;
    if (weekday === targetDay) {
      return formatInTimeZone(cursor, timezone, "yyyy-MM-dd");
    }
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  throw new Error("Could not resolve a future local weekday");
}

function plusLocalDays(localDate: string, days: number): string {
  const cursor = new Date(`${localDate}T00:00:00.000Z`);
  cursor.setUTCDate(cursor.getUTCDate() + days);
  return cursor.toISOString().slice(0, 10);
}

async function createOffer(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  timezone: string,
  suffix: string
): Promise<CoachingOfferDto> {
  const response = await request.post(`${API_URL}/coaching-offers`, {
    headers: auth,
    data: {
      title: { en: `Prep Coaching ${suffix}` },
      description: { en: "E2E prep questionnaire coverage" },
      currency: "EUR",
      priceCents: 0,
      sessionDurationMinutes: 60,
      meetingType: "video",
      availabilityRule: {
        timezone,
        weeklySlots: [{ dayOfWeek: 1, startTime: "09:00", endTime: "12:00" }],
        blackouts: [],
      },
      bookingRules: {
        minNoticeHours: 1,
        maxAdvanceDays: 30,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 0,
      },
      contractRequired: false,
      paymentRequired: false,
      localeDefault: "en",
      contractTemplate: null,
      prepFormTemplate: {
        title: { en: "Before we meet" },
        description: { en: "Please tell your coach what you want from this session." },
        questions: [
          {
            key: "goal",
            type: "long_text",
            required: true,
            label: { en: "What is your main goal?" },
          },
          {
            key: "energy",
            type: "single_select",
            required: true,
            label: { en: "How are you arriving?" },
            options: [
              { value: "steady", label: { en: "Steady" } },
              { value: "stretched", label: { en: "Stretched" } },
            ],
          },
        ],
      },
      prepFormSendHoursBeforeSession: 24,
      debriefTemplate: null,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  const body = (await response.json()) as { offer?: CoachingOfferDto };
  if (!body.offer) {
    throw new Error("Offer creation did not return offer");
  }
  return body.offer;
}

async function createCustomer(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  suffix: string
): Promise<string> {
  const response = await request.post(`${API_URL}/customers`, {
    headers: auth,
    data: {
      displayName: `Prep Client ${suffix}`,
      email: `prep-client-${suffix}@example.com`,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  const body = (await response.json()) as { id?: string };
  if (!body.id) {
    throw new Error("Customer creation did not return an id");
  }
  return body.id;
}

async function getAvailability(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  params: { from: string; to: string; timezone: string }
) {
  const response = await request.get(`${API_URL}/coaching/public/offers/${offerId}/availability`, {
    params,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    slots: Array<{
      startAt: string;
      endAt: string;
      displayStart: string;
      displayEnd: string;
    }>;
  };
}

async function createHold(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  slot: { startAt: string; endAt: string },
  suffix: string
) {
  const response = await request.post(`${API_URL}/coaching/public/offers/${offerId}/holds`, {
    data: {
      startAt: slot.startAt,
      endAt: slot.endAt,
      bookedByName: `Prep Client ${suffix}`,
      bookedByEmail: `prep-client-${suffix}@example.com`,
      ttlSeconds: 600,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    hold: { id: string; startAt: string; endAt: string };
  };
}

async function startBooking(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  offer: CoachingOfferDto,
  hold: { id: string; startAt: string; endAt: string },
  clientPartyId: string
) {
  if (!offer.coachUserId) {
    throw new Error("Offer did not include coachUserId");
  }
  const response = await request.post(`${API_URL}/coaching-engagements`, {
    headers: auth,
    data: {
      clientPartyId,
      bookingHoldId: hold.id,
      coachUserId: offer.coachUserId,
      locale: "en",
      offer: {
        title: offer.title,
        description: offer.description ?? undefined,
        currency: offer.currency,
        priceCents: offer.priceCents,
        sessionDurationMinutes: offer.sessionDurationMinutes,
        meetingType: offer.meetingType,
        availabilityRule: offer.availabilityRule,
        bookingRules: offer.bookingRules,
        contractRequired: offer.contractRequired,
        paymentRequired: offer.paymentRequired,
        localeDefault: offer.localeDefault,
        contractTemplate: offer.contractTemplate ?? null,
        contractLabel: offer.contractLabel ?? undefined,
        prepFormTemplate: offer.prepFormTemplate ?? null,
        prepFormSendHoursBeforeSession: offer.prepFormSendHoursBeforeSession ?? null,
        debriefTemplate: offer.debriefTemplate ?? null,
      },
      session: {
        startAt: hold.startAt,
        endAt: hold.endAt,
      },
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    engagement: { id: string; status: string };
    session: { id: string };
  };
}

async function runWorkerTick(request: import("@playwright/test").APIRequestContext) {
  const serviceToken = process.env.WORKER_API_SERVICE_TOKEN?.trim();
  const legacyWorkerKey = process.env.INTERNAL_WORKER_KEY?.trim();
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (serviceToken) {
    headers["x-service-token"] = serviceToken;
  } else if (legacyWorkerKey) {
    headers["x-worker-key"] = legacyWorkerKey;
  }
  const response = await request.post(`${API_URL}/internal/background/outbox/run`, {
    headers,
    data: { limit: 50 },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as Record<string, unknown>;
}

async function getEngagementDetail(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  engagementId: string
) {
  const response = await request.get(`${API_URL}/coaching-engagements/${engagementId}`, {
    headers: auth,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    engagement: {
      id: string;
      status: string;
      clientPartyId: string;
      coachUserId: string;
    };
    sessions: Array<{
      id: string;
      startAt: string;
      endAt: string;
      prepRequestedAt?: string | null;
      prepSubmittedAt?: string | null;
      prepDocumentId?: string | null;
    }>;
    timeline: Array<{ eventType: string }>;
    artifacts: Array<{ kind: string; document: { id: string; title?: string | null } }>;
  };
}

async function getPrepAccess(tenantId: string, sessionId: string) {
  const body = await apiClient.post<{
    prepAccess: {
      sessionId: string;
      engagementId: string;
      clientPartyId: string;
      coachUserId: string;
      prepAccessToken: string | null;
      prepRequestedAt: string | null;
      prepSubmittedAt: string | null;
      prepDocumentId: string | null;
      startAt: string;
      endAt: string;
    } | null;
  }>("/test/coaching/prep-access", { tenantId, sessionId });
  return body.prepAccess;
}

async function updateSessionSchedule(input: {
  tenantId: string;
  sessionId: string;
  startAt: string;
  endAt: string;
}) {
  await apiClient.post("/test/coaching/session-schedule", input);
}

async function getPrepQuestionnaire(
  request: import("@playwright/test").APIRequestContext,
  sessionId: string,
  token: string
) {
  const response = await request.get(`${API_URL}/coaching/public/prep/${sessionId}/${token}`);
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    questionnaire: {
      sessionId: string;
      engagementId: string;
      title: string;
      description?: string | null;
      questions: Array<{ key: string; labelResolved: string }>;
    };
  };
}

async function submitPrep(
  request: import("@playwright/test").APIRequestContext,
  sessionId: string,
  token: string,
  answers: Record<string, unknown>,
  submittedByName: string
) {
  const response = await request.post(`${API_URL}/coaching/public/prep/${sessionId}/${token}`, {
    data: {
      answers,
      submittedByName,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    submitted: true;
    session: { id: string; prepSubmittedAt?: string | null; prepDocumentId?: string | null };
  };
}

async function listDocumentsByEntity(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  entityType: string,
  entityId: string
) {
  const response = await request.get(`${API_URL}/documents/by-entity`, {
    headers: auth,
    params: { entityType, entityId },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    items: Array<{ id: string; title?: string | null }>;
  };
}

async function downloadDocumentText(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  documentId: string
) {
  const response = await request.get(`${API_URL}/documents/${documentId}/download`, {
    headers: auth,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  const bytes = await response.body();
  return Buffer.from(bytes).toString("utf8");
}

test.describe("Coaching prep questionnaire", () => {
  test("sends the prep form at the configured time, avoids duplicate reminders, and saves the response for the coach on the client profile", async ({
    page,
    request,
    testData,
  }, testInfo) => {
    const screenshotDir = screenshotDirFor(testInfo);
    const suffix = uniqueSuffix();
    const auth = await loginAsSeededUser(request, testData);
    const headers = buildAuthHeaders(auth);
    const offerTimezone = "America/New_York";
    const viewerTimezone = "Europe/Berlin";

    const offer = await createOffer(request, headers, offerTimezone, suffix);
    expect(offer.prepFormSendHoursBeforeSession).toBe(24);

    const localMonday = nextLocalWeekday(1, offerTimezone, 8);
    const rangeStart = fromZonedTime(`${localMonday}T00:00:00`, offerTimezone).toISOString();
    const rangeEnd = fromZonedTime(
      `${plusLocalDays(localMonday, 1)}T00:00:00`,
      offerTimezone
    ).toISOString();
    const availability = await getAvailability(request, offer.id, {
      from: rangeStart,
      to: rangeEnd,
      timezone: viewerTimezone,
    });
    expect(availability.slots).toHaveLength(3);

    const clientPartyId = await createCustomer(request, headers, suffix);
    const hold = await createHold(request, offer.id, availability.slots[0], suffix);
    const booking = await startBooking(request, headers, offer, hold.hold, clientPartyId);
    expect(booking.engagement.status).toBe("prep_pending");

    await runWorkerTick(request);

    let detail = await getEngagementDetail(request, headers, booking.engagement.id);
    expect(detail.sessions[0]?.prepRequestedAt).toBeNull();
    expect(
      detail.timeline.filter((entry) => entry.eventType === "coaching.prep_form.requested")
    ).toHaveLength(0);

    await captureState(page, testInfo, screenshotDir, "01-before-prep-is-due", "Prep not due yet", {
      engagement: detail.engagement,
      session: detail.sessions[0],
      timeline: detail.timeline,
    });

    const dueStartAt = new Date(Date.now() + 23 * 60 * 60 * 1000).toISOString();
    const dueEndAt = new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString();
    await updateSessionSchedule({
      tenantId: testData.tenant.id,
      sessionId: booking.session.id,
      startAt: dueStartAt,
      endAt: dueEndAt,
    });

    await runWorkerTick(request);

    detail = await getEngagementDetail(request, headers, booking.engagement.id);
    expect(detail.sessions[0]?.prepRequestedAt).toBeTruthy();
    expect(
      detail.timeline.filter((entry) => entry.eventType === "coaching.prep_form.requested")
    ).toHaveLength(1);

    const prepAccess = await getPrepAccess(testData.tenant.id, booking.session.id);
    expect(prepAccess?.prepAccessToken).toBeTruthy();
    expect(prepAccess?.prepRequestedAt).toBe(detail.sessions[0]?.prepRequestedAt ?? null);
    const prepUrl = `${API_URL}/coaching/public/prep/${booking.session.id}/${prepAccess!.prepAccessToken}`;

    const questionnaire = await getPrepQuestionnaire(
      request,
      booking.session.id,
      prepAccess!.prepAccessToken!
    );
    expect(questionnaire.questionnaire.sessionId).toBe(booking.session.id);
    expect(questionnaire.questionnaire.engagementId).toBe(booking.engagement.id);
    expect(questionnaire.questionnaire.title).toBe("Before we meet");
    expect(questionnaire.questionnaire.questions.map((question) => question.key)).toEqual([
      "goal",
      "energy",
    ]);

    await captureState(page, testInfo, screenshotDir, "02-prep-link-ready", "Prep link ready", {
      prepUrl,
      prepAccess,
      questionnaire,
    });

    const firstPrepRequestedAt = detail.sessions[0]?.prepRequestedAt ?? null;
    await runWorkerTick(request);
    detail = await getEngagementDetail(request, headers, booking.engagement.id);
    const prepAccessAfterRetry = await getPrepAccess(testData.tenant.id, booking.session.id);
    expect(
      detail.timeline.filter((entry) => entry.eventType === "coaching.prep_form.requested")
    ).toHaveLength(1);
    expect(detail.sessions[0]?.prepRequestedAt).toBe(firstPrepRequestedAt);
    expect(prepAccessAfterRetry?.prepAccessToken).toBe(prepAccess?.prepAccessToken ?? null);

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "03-prep-reminder-not-duplicated",
      "Prep reminder not duplicated",
      {
        firstPrepRequestedAt,
        prepAccessAfterRetry,
        timeline: detail.timeline,
      }
    );

    const answers = {
      goal: `Prepare for a decisive planning session ${suffix}`,
      energy: "stretched",
    };
    const submittedByName = `Prep Client ${suffix}`;
    const submission = await submitPrep(
      request,
      booking.session.id,
      prepAccess!.prepAccessToken!,
      answers,
      submittedByName
    );
    expect(submission.submitted).toBe(true);

    detail = await getEngagementDetail(request, headers, booking.engagement.id);
    expect(detail.engagement.status).toBe("ready");
    expect(detail.sessions[0]?.prepSubmittedAt).toBeTruthy();
    expect(detail.sessions[0]?.prepDocumentId).toBeTruthy();
    expect(detail.artifacts.some((artifact) => artifact.kind === "prep_response")).toBe(true);

    const partyDocuments = await listDocumentsByEntity(
      request,
      headers,
      "PARTY",
      detail.engagement.clientPartyId
    );
    expect(
      partyDocuments.items.some((document) => document.id === detail.sessions[0]?.prepDocumentId)
    ).toBe(true);

    const prepDocumentText = await downloadDocumentText(
      request,
      headers,
      detail.sessions[0]!.prepDocumentId!
    );
    expect(prepDocumentText).toContain(`Prep response for session ${booking.session.id}`);
    expect(prepDocumentText).toContain(`Submitted by: ${submittedByName}`);
    expect(prepDocumentText).toContain(`goal: ${JSON.stringify(answers.goal)}`);
    expect(prepDocumentText).toContain(`energy: ${JSON.stringify(answers.energy)}`);

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "04-prep-response-saved",
      "Prep response saved",
      {
        engagement: detail.engagement,
        session: detail.sessions[0],
        artifacts: detail.artifacts,
        partyDocuments,
        prepDocumentSnippet: prepDocumentText.slice(0, 500),
      }
    );

    console.log(`Coaching prep questionnaire screenshots saved to ${screenshotDir}`);
  });
});
