import { expect, type Page, type TestInfo } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { formatInTimeZone, fromZonedTime } from "date-fns-tz";
import { test } from "./fixtures.ts";
import type { CoachingOfferDto } from "@corely/contracts";
import { buildAuthHeaders, loginAsSeededUser } from "./helpers/auth.ts";

const API_URL = process.env.API_URL ?? "http://localhost:3000";
const SCREENSHOT_STAMP = new Date().toISOString().replace(/[:.]/g, "-");
const E2E_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function screenshotDirFor(testInfo: TestInfo): string {
  const dir = join(
    E2E_ROOT,
    "output",
    "coaching-public-booking-e2e",
    SCREENSHOT_STAMP,
    testInfo.project.name,
    slugify(testInfo.title)
  );
  mkdirSync(dir, { recursive: true });
  return dir;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

async function captureState(
  page: Page,
  testInfo: TestInfo,
  screenshotDir: string,
  name: string,
  title: string,
  payload: unknown
): Promise<void> {
  const formatted = escapeHtml(JSON.stringify(payload, null, 2));
  await page.setContent(
    `<!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>${escapeHtml(title)}</title>
        <style>
          :root {
            color-scheme: light;
            font-family: "IBM Plex Sans", "Helvetica Neue", sans-serif;
          }
          body {
            margin: 0;
            background: linear-gradient(180deg, #f4f7fb 0%, #e8eef7 100%);
            color: #112240;
          }
          main {
            padding: 32px;
          }
          h1 {
            margin: 0 0 12px;
            font-size: 28px;
          }
          p {
            margin: 0 0 20px;
            color: #42526e;
            font-size: 14px;
          }
          pre {
            margin: 0;
            padding: 20px;
            border-radius: 16px;
            background: #0f172a;
            color: #e2e8f0;
            font: 13px/1.5 "SFMono-Regular", "Menlo", monospace;
            white-space: pre-wrap;
            word-break: break-word;
            box-shadow: 0 20px 45px rgba(15, 23, 42, 0.16);
          }
        </style>
      </head>
      <body>
        <main>
          <h1>${escapeHtml(title)}</h1>
          <p>Generated by the coaching public booking e2e flow.</p>
          <pre>${formatted}</pre>
        </main>
      </body>
    </html>`
  );
  await page.setViewportSize({ width: 1440, height: 1200 });
  await page.waitForLoadState("networkidle").catch(() => undefined);
  const path = join(screenshotDir, `${name}.png`);
  await page.screenshot({ path, fullPage: true });
  await testInfo.attach(name, {
    path,
    contentType: "image/png",
  });
}

function uniqueSuffix() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function nextLocalWeekday(targetDay: number, timezone: string, minDaysAhead = 7): string {
  const cursor = new Date(Date.now() + minDaysAhead * 24 * 60 * 60 * 1000);
  for (let attempts = 0; attempts < 21; attempts += 1) {
    const weekday = Number(formatInTimeZone(cursor, timezone, "i")) % 7;
    if (weekday === targetDay) {
      return formatInTimeZone(cursor, timezone, "yyyy-MM-dd");
    }
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  throw new Error("Could not resolve a future local weekday");
}

function plusLocalDays(localDate: string, days: number): string {
  const cursor = new Date(`${localDate}T00:00:00.000Z`);
  cursor.setUTCDate(cursor.getUTCDate() + days);
  return cursor.toISOString().slice(0, 10);
}

async function createCustomer(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  suffix: string
): Promise<string> {
  const response = await request.post(`${API_URL}/customers`, {
    headers: auth,
    data: {
      displayName: `Coaching Client ${suffix}`,
      email: `coaching-client-${suffix}@example.com`,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  const body = (await response.json()) as { id?: string };
  if (!body.id) {
    throw new Error("Customer creation did not return an id");
  }
  return body.id;
}

async function createOffer(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  timezone: string,
  suffix: string
): Promise<CoachingOfferDto> {
  const response = await request.post(`${API_URL}/coaching-offers`, {
    headers: auth,
    data: {
      title: { en: `Public Coaching ${suffix}` },
      description: { en: "E2E public booking coverage" },
      currency: "EUR",
      priceCents: 22000,
      sessionDurationMinutes: 60,
      meetingType: "video",
      availabilityRule: {
        timezone,
        weeklySlots: [{ dayOfWeek: 1, startTime: "09:00", endTime: "12:00" }],
        blackouts: [],
      },
      bookingRules: {
        minNoticeHours: 1,
        maxAdvanceDays: 30,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 0,
      },
      contractRequired: true,
      paymentRequired: true,
      localeDefault: "en",
      contractTemplate: { en: "Standard coaching agreement" },
      prepFormTemplate: null,
      debriefTemplate: null,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  const body = (await response.json()) as { offer?: CoachingOfferDto };
  if (!body.offer) {
    throw new Error("Offer creation did not return offer");
  }
  return body.offer;
}

async function getAvailability(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  params: { from: string; to: string; timezone: string }
) {
  const response = await request.get(`${API_URL}/coaching/public/offers/${offerId}/availability`, {
    params,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    offerId: string;
    offerTimezone: string;
    displayTimezone: string;
    slots: Array<{
      startAt: string;
      endAt: string;
      displayStart: string;
      displayEnd: string;
    }>;
  };
}

test.describe("Coaching public booking", () => {
  test("available slots, conflict blocking, timezone conversion, and slot release all work", async ({
    page,
    request,
    testData,
  }, testInfo) => {
    const screenshotDir = screenshotDirFor(testInfo);
    const suffix = uniqueSuffix();
    const auth = await loginAsSeededUser(request, testData);
    const headers = buildAuthHeaders(auth);
    const offerTimezone = "America/New_York";
    const viewerTimezone = "Europe/Berlin";

    const customerId = await createCustomer(request, headers, suffix);
    const offer = await createOffer(request, headers, offerTimezone, suffix);

    expect(offer.coachUserId).toBe(testData.user.id);

    const localMonday = nextLocalWeekday(1, offerTimezone, 8);
    const rangeStart = fromZonedTime(`${localMonday}T00:00:00`, offerTimezone).toISOString();
    const rangeEnd = fromZonedTime(`${plusLocalDays(localMonday, 1)}T00:00:00`, offerTimezone).toISOString();

    const initialAvailability = await getAvailability(request, offer.id, {
      from: rangeStart,
      to: rangeEnd,
      timezone: viewerTimezone,
    });

    expect(initialAvailability.offerTimezone).toBe(offerTimezone);
    expect(initialAvailability.displayTimezone).toBe(viewerTimezone);
    expect(initialAvailability.slots).toHaveLength(3);

    const expectedFirstStartUtc = fromZonedTime(`${localMonday}T09:00:00`, offerTimezone).toISOString();
    const expectedFirstStartViewer = formatInTimeZone(
      new Date(expectedFirstStartUtc),
      viewerTimezone,
      "yyyy-MM-dd'T'HH:mm:ssXXX"
    );
    expect(initialAvailability.slots[0].startAt).toBe(expectedFirstStartUtc);
    expect(initialAvailability.slots[0].displayStart).toBe(expectedFirstStartViewer);
    await captureState(page, testInfo, screenshotDir, "01-initial-availability", "Initial availability", {
      offerId: offer.id,
      offerTimezone,
      viewerTimezone,
      localMonday,
      slots: initialAvailability.slots,
    });

    const unavailableHold = await request.post(`${API_URL}/coaching/public/offers/${offer.id}/holds`, {
      data: {
        startAt: fromZonedTime(`${localMonday}T13:00:00`, offerTimezone).toISOString(),
        endAt: fromZonedTime(`${localMonday}T14:00:00`, offerTimezone).toISOString(),
        bookedByName: "Unavailable Client",
        bookedByEmail: `unavailable-${suffix}@example.com`,
        ttlSeconds: 5,
      },
    });
    expect(unavailableHold.status()).toBe(409);
    await captureState(
      page,
      testInfo,
      screenshotDir,
      "02-unavailable-slot-blocked",
      "Unavailable slot blocked",
      {
        status: unavailableHold.status(),
        attemptedStartAt: fromZonedTime(`${localMonday}T13:00:00`, offerTimezone).toISOString(),
        attemptedEndAt: fromZonedTime(`${localMonday}T14:00:00`, offerTimezone).toISOString(),
      }
    );

    const heldSlot = initialAvailability.slots[0];
    const shortHoldResponse = await request.post(
      `${API_URL}/coaching/public/offers/${offer.id}/holds`,
      {
        data: {
          startAt: heldSlot.startAt,
          endAt: heldSlot.endAt,
          bookedByName: "Holding Client",
          bookedByEmail: `hold-${suffix}@example.com`,
          ttlSeconds: 1,
        },
      }
    );
    expect(shortHoldResponse.ok(), await shortHoldResponse.text()).toBeTruthy();

    const duplicateHoldResponse = await request.post(
      `${API_URL}/coaching/public/offers/${offer.id}/holds`,
      {
        data: {
          startAt: heldSlot.startAt,
          endAt: heldSlot.endAt,
          bookedByName: "Second Client",
          bookedByEmail: `hold-second-${suffix}@example.com`,
          ttlSeconds: 30,
        },
      }
    );
    expect(duplicateHoldResponse.status()).toBe(409);

    const blockedAvailability = await getAvailability(request, offer.id, {
      from: rangeStart,
      to: rangeEnd,
      timezone: viewerTimezone,
    });
    expect(blockedAvailability.slots.map((slot) => slot.startAt)).not.toContain(heldSlot.startAt);
    await captureState(page, testInfo, screenshotDir, "03-held-slot-removed", "Held slot removed from availability", {
      heldSlot,
      duplicateHoldStatus: duplicateHoldResponse.status(),
      remainingSlots: blockedAvailability.slots,
    });

    await new Promise((resolve) => setTimeout(resolve, 1500));

    const postExpiryAvailability = await getAvailability(request, offer.id, {
      from: rangeStart,
      to: rangeEnd,
      timezone: viewerTimezone,
    });
    expect(postExpiryAvailability.slots.map((slot) => slot.startAt)).toContain(heldSlot.startAt);
    await captureState(page, testInfo, screenshotDir, "04-expired-slot-returned", "Expired slot returned", {
      returnedSlot: heldSlot,
      slots: postExpiryAvailability.slots,
    });

    const bookedSlot = initialAvailability.slots[1];
    const bookingResponse = await request.post(`${API_URL}/coaching-engagements`, {
      headers,
      data: {
        clientPartyId: customerId,
        coachUserId: testData.user.id,
        locale: "en",
        offer: {
          title: offer.title,
          description: offer.description,
          currency: offer.currency,
          priceCents: offer.priceCents,
          sessionDurationMinutes: offer.sessionDurationMinutes,
          meetingType: offer.meetingType,
          availabilityRule: offer.availabilityRule,
          bookingRules: offer.bookingRules,
          contractRequired: offer.contractRequired,
          paymentRequired: offer.paymentRequired,
          localeDefault: offer.localeDefault,
          contractTemplate: offer.contractTemplate,
          contractLabel: offer.contractLabel,
          prepFormTemplate: offer.prepFormTemplate,
          debriefTemplate: offer.debriefTemplate,
        },
        session: {
          startAt: bookedSlot.startAt,
          endAt: bookedSlot.endAt,
          meetingProvider: "manual",
        },
      },
    });
    expect(bookingResponse.ok(), await bookingResponse.text()).toBeTruthy();
    const bookingBody = (await bookingResponse.json()) as {
      session: { id: string };
    };

    const doubleBookResponse = await request.post(
      `${API_URL}/coaching/public/offers/${offer.id}/holds`,
      {
        data: {
          startAt: bookedSlot.startAt,
          endAt: bookedSlot.endAt,
          bookedByName: "Blocked Client",
          bookedByEmail: `blocked-${suffix}@example.com`,
          ttlSeconds: 30,
        },
      }
    );
    expect(doubleBookResponse.status()).toBe(409);
    await captureState(page, testInfo, screenshotDir, "05-double-booking-blocked", "Double booking blocked", {
      bookedSlot,
      bookingStatus: bookingResponse.status(),
      doubleBookStatus: doubleBookResponse.status(),
    });

    const postBookingAvailability = await getAvailability(request, offer.id, {
      from: rangeStart,
      to: rangeEnd,
      timezone: viewerTimezone,
    });
    expect(postBookingAvailability.slots.map((slot) => slot.startAt)).not.toContain(bookedSlot.startAt);
    await captureState(page, testInfo, screenshotDir, "06-booked-slot-removed", "Booked slot removed from availability", {
      slots: postBookingAvailability.slots,
    });

    const cancelResponse = await request.post(
      `${API_URL}/coaching-sessions/${bookingBody.session.id}/cancel`,
      {
        headers,
        data: { reason: "Client requested a different time" },
      }
    );
    expect(cancelResponse.ok(), await cancelResponse.text()).toBeTruthy();

    const postCancelAvailability = await getAvailability(request, offer.id, {
      from: rangeStart,
      to: rangeEnd,
      timezone: viewerTimezone,
    });
    expect(postCancelAvailability.slots.map((slot) => slot.startAt)).toContain(bookedSlot.startAt);
    await captureState(page, testInfo, screenshotDir, "07-cancelled-slot-returned", "Cancelled slot returned", {
      cancelledSessionId: bookingBody.session.id,
      slots: postCancelAvailability.slots,
    });

    console.log(`Coaching public booking screenshots saved to ${screenshotDir}`);
  });
});
