import { expect, type Page, type TestInfo } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { formatInTimeZone, fromZonedTime } from "date-fns-tz";
import { test } from "./fixtures.ts";
import type { CoachingOfferDto } from "@corely/contracts";
import { signFakeStripeWebhook } from "./helpers/billing-fixtures.ts";
import { buildAuthHeaders, loginAsSeededUser } from "./helpers/auth.ts";

const API_URL = process.env.API_URL ?? "http://localhost:3000";
const SCREENSHOT_STAMP = new Date().toISOString().replace(/[:.]/g, "-");
const E2E_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

function uniqueSuffix() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function screenshotDirFor(testInfo: TestInfo): string {
  const dir = join(
    E2E_ROOT,
    "output",
    "coaching-payment-booking-e2e",
    SCREENSHOT_STAMP,
    testInfo.project.name,
    slugify(testInfo.title)
  );
  mkdirSync(dir, { recursive: true });
  return dir;
}

function escapeHtml(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

async function captureState(
  page: Page,
  testInfo: TestInfo,
  screenshotDir: string,
  name: string,
  title: string,
  payload: unknown
) {
  const formatted = escapeHtml(JSON.stringify(payload, null, 2));
  await page.setContent(
    `<!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>${escapeHtml(title)}</title>
        <style>
          body {
            margin: 0;
            background: linear-gradient(180deg, #f8fafc 0%, #e2e8f0 100%);
            color: #0f172a;
            font-family: "IBM Plex Sans", sans-serif;
          }
          main { padding: 32px; }
          h1 { margin: 0 0 12px; font-size: 28px; }
          p { margin: 0 0 18px; color: #334155; }
          pre {
            margin: 0;
            padding: 20px;
            border-radius: 16px;
            background: #020617;
            color: #e2e8f0;
            font: 13px/1.5 "SFMono-Regular", monospace;
            white-space: pre-wrap;
            word-break: break-word;
          }
        </style>
      </head>
      <body>
        <main>
          <h1>${escapeHtml(title)}</h1>
          <p>Generated by the coaching payment during booking e2e flow.</p>
          <pre>${formatted}</pre>
        </main>
      </body>
    </html>`
  );
  await page.setViewportSize({ width: 1440, height: 1200 });
  const path = join(screenshotDir, `${name}.png`);
  await page.screenshot({ path, fullPage: true });
  await testInfo.attach(name, { path, contentType: "image/png" });
}

function nextLocalWeekday(targetDay: number, timezone: string, minDaysAhead = 7): string {
  const cursor = new Date(Date.now() + minDaysAhead * 24 * 60 * 60 * 1000);
  for (let attempts = 0; attempts < 21; attempts += 1) {
    const weekday = Number(formatInTimeZone(cursor, timezone, "i")) % 7;
    if (weekday === targetDay) {
      return formatInTimeZone(cursor, timezone, "yyyy-MM-dd");
    }
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  throw new Error("Could not resolve a future local weekday");
}

function plusLocalDays(localDate: string, days: number): string {
  const cursor = new Date(`${localDate}T00:00:00.000Z`);
  cursor.setUTCDate(cursor.getUTCDate() + days);
  return cursor.toISOString().slice(0, 10);
}

async function createOffer(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  timezone: string,
  suffix: string
): Promise<CoachingOfferDto> {
  const response = await request.post(`${API_URL}/coaching-offers`, {
    headers: auth,
    data: {
      title: { en: `Paid Coaching ${suffix}` },
      description: { en: "E2E payment coverage" },
      currency: "EUR",
      priceCents: 32000,
      sessionDurationMinutes: 60,
      meetingType: "video",
      availabilityRule: {
        timezone,
        weeklySlots: [{ dayOfWeek: 1, startTime: "09:00", endTime: "12:00" }],
        blackouts: [],
      },
      bookingRules: {
        minNoticeHours: 1,
        maxAdvanceDays: 30,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 0,
      },
      contractRequired: false,
      paymentRequired: true,
      localeDefault: "en",
      contractTemplate: null,
      prepFormTemplate: null,
      debriefTemplate: null,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  const body = (await response.json()) as { offer?: CoachingOfferDto };
  if (!body.offer) {
    throw new Error("Offer creation did not return offer");
  }
  return body.offer;
}

async function getAvailability(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  params: { from: string; to: string; timezone: string }
) {
  const response = await request.get(`${API_URL}/coaching/public/offers/${offerId}/availability`, {
    params,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    offerId: string;
    offerTimezone: string;
    displayTimezone: string;
    slots: Array<{
      startAt: string;
      endAt: string;
      displayStart: string;
      displayEnd: string;
    }>;
  };
}

async function createHold(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  slot: { startAt: string; endAt: string },
  suffix: string
) {
  const response = await request.post(`${API_URL}/coaching/public/offers/${offerId}/holds`, {
    data: {
      startAt: slot.startAt,
      endAt: slot.endAt,
      bookedByName: `Client ${suffix}`,
      bookedByEmail: `client-${suffix}@example.com`,
      ttlSeconds: 600,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    hold: { id: string; expiresAt: string; startAt: string; endAt: string };
  };
}

async function startBooking(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  holdId: string,
  suffix: string
) {
  const response = await request.post(`${API_URL}/coaching/public/offers/${offerId}/bookings`, {
    data: {
      holdId,
      locale: "en",
      client: {
        displayName: `Client ${suffix}`,
        email: `client-${suffix}@example.com`,
      },
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    engagement: { id: string; status: string; paymentStatus: string };
    session: { id: string };
    payment: {
      id: string;
      status: string;
      providerCheckoutSessionId: string | null;
      providerCheckoutUrl: string | null;
    };
    checkoutUrl: string;
  };
}

async function getEngagementDetail(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  engagementId: string
) {
  const response = await request.get(`${API_URL}/coaching-engagements/${engagementId}`, {
    headers: auth,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    engagement: { id: string; status: string; paymentStatus: string };
    sessions: Array<{ id: string; status: string; startAt: string; endAt: string }>;
    payments: Array<{
      id: string;
      status: string;
      provider: string;
      providerCheckoutSessionId: string | null;
      providerPaymentRef: string | null;
      providerRefundRef: string | null;
      refundedAmountCents: number;
    }>;
    timeline: Array<{ eventType: string }>;
  };
}

async function postStripeWebhook(
  request: import("@playwright/test").APIRequestContext,
  event: Record<string, unknown>
) {
  const rawBody = JSON.stringify(event);
  const signature = signFakeStripeWebhook(rawBody, "test-coaching-webhook-secret");
  const response = await request.post(`${API_URL}/coaching-engagements/webhooks/stripe`, {
    headers: {
      "Content-Type": "application/json",
      "stripe-signature": signature,
    },
    data: rawBody,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
}

test.describe("Coaching payment during booking", () => {
  test("captures payment, rejects duplicate webhook, keeps failed bookings unconfirmed, and refunds correctly", async ({
    page,
    request,
    testData,
  }, testInfo) => {
    const screenshotDir = screenshotDirFor(testInfo);
    const suffix = uniqueSuffix();
    const auth = await loginAsSeededUser(request, testData);
    const headers = buildAuthHeaders(auth);
    const offerTimezone = "America/New_York";
    const viewerTimezone = "Europe/Berlin";

    const offer = await createOffer(request, headers, offerTimezone, suffix);
    const localMonday = nextLocalWeekday(1, offerTimezone, 8);
    const rangeStart = fromZonedTime(`${localMonday}T00:00:00`, offerTimezone).toISOString();
    const rangeEnd = fromZonedTime(
      `${plusLocalDays(localMonday, 1)}T00:00:00`,
      offerTimezone
    ).toISOString();
    const initialAvailability = await getAvailability(request, offer.id, {
      from: rangeStart,
      to: rangeEnd,
      timezone: viewerTimezone,
    });
    expect(initialAvailability.slots).toHaveLength(3);

    const firstHold = await createHold(request, offer.id, initialAvailability.slots[0], suffix);
    const firstBooking = await startBooking(request, offer.id, firstHold.hold.id, suffix);
    expect(firstBooking.payment.status).toBe("pending");
    expect(firstBooking.engagement.paymentStatus).toBe("pending");

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "01-booking-pending-payment",
      "Pending payment booking",
      {
        offerId: offer.id,
        booking: firstBooking,
      }
    );

    const pendingDetail = await getEngagementDetail(request, headers, firstBooking.engagement.id);
    expect(pendingDetail.payments).toHaveLength(1);
    expect(pendingDetail.payments[0]?.status).toBe("pending");

    const successEvent = {
      id: `evt_success_${suffix}`,
      type: "checkout.session.completed",
      data: {
        object: {
          id: firstBooking.payment.providerCheckoutSessionId,
          object: "checkout.session",
          payment_intent: `pi_success_${suffix}`,
          metadata: {
            tenantId: testData.tenant.id,
            engagementId: firstBooking.engagement.id,
            paymentId: firstBooking.payment.id,
          },
        },
      },
    };
    await postStripeWebhook(request, successEvent);

    const capturedDetail = await getEngagementDetail(request, headers, firstBooking.engagement.id);
    expect(capturedDetail.engagement.paymentStatus).toBe("captured");
    expect(capturedDetail.engagement.status).toBe("ready");
    expect(capturedDetail.payments[0]?.status).toBe("captured");
    expect(
      capturedDetail.timeline.filter((entry) => entry.eventType === "coaching.payment.captured")
    ).toHaveLength(1);

    await captureState(page, testInfo, screenshotDir, "02-payment-captured", "Payment captured", {
      engagement: capturedDetail.engagement,
      payments: capturedDetail.payments,
      timeline: capturedDetail.timeline,
    });

    await postStripeWebhook(request, successEvent);
    const duplicateDetail = await getEngagementDetail(request, headers, firstBooking.engagement.id);
    expect(duplicateDetail.payments).toHaveLength(1);
    expect(
      duplicateDetail.timeline.filter((entry) => entry.eventType === "coaching.payment.captured")
    ).toHaveLength(1);

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "03-duplicate-webhook-ignored",
      "Duplicate webhook ignored",
      {
        payments: duplicateDetail.payments,
        timeline: duplicateDetail.timeline,
      }
    );

    const secondHold = await createHold(
      request,
      offer.id,
      initialAvailability.slots[1],
      `${suffix}-failed`
    );
    const secondBooking = await startBooking(
      request,
      offer.id,
      secondHold.hold.id,
      `${suffix}-failed`
    );

    const failureEvent = {
      id: `evt_failed_${suffix}`,
      type: "payment_intent.payment_failed",
      data: {
        object: {
          id: `pi_failed_${suffix}`,
          object: "payment_intent",
          metadata: {
            tenantId: testData.tenant.id,
            engagementId: secondBooking.engagement.id,
            paymentId: secondBooking.payment.id,
          },
          failure_code: "card_declined",
          failure_message: "Card was declined",
        },
      },
    };
    await postStripeWebhook(request, failureEvent);

    const failedDetail = await getEngagementDetail(request, headers, secondBooking.engagement.id);
    expect(failedDetail.engagement.paymentStatus).toBe("failed");
    expect(failedDetail.engagement.status).toBe("pending_payment");
    expect(failedDetail.payments[0]?.status).toBe("failed");
    expect(failedDetail.sessions[0]?.status).toBe("cancelled");

    const postFailureAvailability = await getAvailability(request, offer.id, {
      from: rangeStart,
      to: rangeEnd,
      timezone: viewerTimezone,
    });
    expect(postFailureAvailability.slots.map((slot) => slot.startAt)).toContain(
      initialAvailability.slots[1]?.startAt
    );

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "04-failed-payment-released-slot",
      "Failed payment keeps booking unconfirmed",
      {
        engagement: failedDetail.engagement,
        payments: failedDetail.payments,
        sessions: failedDetail.sessions,
        availability: postFailureAvailability.slots,
      }
    );

    const refundResponse = await request.post(
      `${API_URL}/coaching-engagements/${firstBooking.engagement.id}/refund`,
      {
        headers,
        data: {
          paymentId: firstBooking.payment.id,
          reason: "Client requested a refund",
        },
      }
    );
    expect(refundResponse.ok(), await refundResponse.text()).toBeTruthy();

    const refundedDetail = await getEngagementDetail(request, headers, firstBooking.engagement.id);
    expect(refundedDetail.payments[0]?.status).toBe("refunded");
    expect(refundedDetail.payments[0]?.providerRefundRef).toBeTruthy();

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "05-refund-updated",
      "Refund updated payment status",
      {
        payments: refundedDetail.payments,
        timeline: refundedDetail.timeline,
      }
    );

    console.log(`Coaching payment booking screenshots saved to ${screenshotDir}`);
  });
});
