import { expect, type Page, type TestInfo } from "@playwright/test";
import { mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { formatInTimeZone, fromZonedTime } from "date-fns-tz";
import { test } from "./fixtures.ts";
import type { CoachingOfferDto } from "@corely/contracts";
import { signFakeStripeWebhook } from "./helpers/billing-fixtures.ts";
import { buildAuthHeaders, loginAsSeededUser } from "./helpers/auth.ts";
import { apiClient } from "../utils/api.ts";
import Stripe from "stripe";

const API_URL = process.env.API_URL ?? "http://localhost:3000";
const SCREENSHOT_STAMP = new Date().toISOString().replace(/[:.]/g, "-");
const E2E_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

function uniqueSuffix() {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}

function screenshotDirFor(testInfo: TestInfo): string {
  const dir = join(
    E2E_ROOT,
    "output",
    "coaching-contract-signature-e2e",
    SCREENSHOT_STAMP,
    testInfo.project.name,
    slugify(testInfo.title)
  );
  mkdirSync(dir, { recursive: true });
  return dir;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

async function captureState(
  page: Page,
  testInfo: TestInfo,
  screenshotDir: string,
  name: string,
  title: string,
  payload: unknown
) {
  const formatted = escapeHtml(JSON.stringify(payload, null, 2));
  await page.setContent(
    `<!doctype html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <title>${escapeHtml(title)}</title>
        <style>
          body {
            margin: 0;
            background: linear-gradient(180deg, #fff7ed 0%, #ffedd5 100%);
            color: #431407;
            font-family: "IBM Plex Sans", sans-serif;
          }
          main { padding: 32px; }
          h1 { margin: 0 0 12px; font-size: 28px; }
          p { margin: 0 0 18px; color: #7c2d12; }
          pre {
            margin: 0;
            padding: 20px;
            border-radius: 16px;
            background: #1c1917;
            color: #fed7aa;
            font: 13px/1.5 "SFMono-Regular", monospace;
            white-space: pre-wrap;
            word-break: break-word;
          }
        </style>
      </head>
      <body>
        <main>
          <h1>${escapeHtml(title)}</h1>
          <p>Generated by the coaching contract signature e2e flow.</p>
          <pre>${formatted}</pre>
        </main>
      </body>
    </html>`
  );
  await page.setViewportSize({ width: 1440, height: 1200 });
  await page.waitForLoadState("networkidle").catch(() => undefined);
  const path = join(screenshotDir, `${name}.png`);
  await page.screenshot({ path, fullPage: true });
  await testInfo.attach(name, { path, contentType: "image/png" });
}

function nextLocalWeekday(targetDay: number, timezone: string, minDaysAhead = 7): string {
  const cursor = new Date(Date.now() + minDaysAhead * 24 * 60 * 60 * 1000);
  for (let attempts = 0; attempts < 21; attempts += 1) {
    const weekday = Number(formatInTimeZone(cursor, timezone, "i")) % 7;
    if (weekday === targetDay) {
      return formatInTimeZone(cursor, timezone, "yyyy-MM-dd");
    }
    cursor.setUTCDate(cursor.getUTCDate() + 1);
  }
  throw new Error("Could not resolve a future local weekday");
}

function plusLocalDays(localDate: string, days: number): string {
  const cursor = new Date(`${localDate}T00:00:00.000Z`);
  cursor.setUTCDate(cursor.getUTCDate() + days);
  return cursor.toISOString().slice(0, 10);
}

async function sleep(ms: number) {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

async function createOffer(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  timezone: string,
  suffix: string
): Promise<CoachingOfferDto> {
  const contractTemplate = [
    `Coaching agreement for ${suffix}`,
    "Clause 1: Payment is already captured before confirmation.",
    "Clause 2: Booking remains unconfirmed until signature is complete.",
  ].join("\n");
  const response = await request.post(`${API_URL}/coaching-offers`, {
    headers: auth,
    data: {
      title: { en: `Contract Coaching ${suffix}` },
      description: { en: "E2E contract signature coverage" },
      currency: "EUR",
      priceCents: 48000,
      sessionDurationMinutes: 60,
      meetingType: "video",
      availabilityRule: {
        timezone,
        weeklySlots: [{ dayOfWeek: 1, startTime: "09:00", endTime: "12:00" }],
        blackouts: [],
      },
      bookingRules: {
        minNoticeHours: 1,
        maxAdvanceDays: 30,
        bufferBeforeMinutes: 0,
        bufferAfterMinutes: 0,
      },
      contractRequired: true,
      paymentRequired: true,
      localeDefault: "en",
      contractTemplate: { en: contractTemplate },
      prepFormTemplate: null,
      debriefTemplate: null,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  const body = (await response.json()) as { offer?: CoachingOfferDto };
  if (!body.offer) {
    throw new Error("Offer creation did not return offer");
  }
  return body.offer;
}

async function getAvailability(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  params: { from: string; to: string; timezone: string }
) {
  const response = await request.get(`${API_URL}/coaching/public/offers/${offerId}/availability`, {
    params,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    offerId: string;
    offerTimezone: string;
    displayTimezone: string;
    slots: Array<{
      startAt: string;
      endAt: string;
      displayStart: string;
      displayEnd: string;
    }>;
  };
}

async function createHold(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  slot: { startAt: string; endAt: string },
  suffix: string
) {
  const response = await request.post(`${API_URL}/coaching/public/offers/${offerId}/holds`, {
    data: {
      startAt: slot.startAt,
      endAt: slot.endAt,
      bookedByName: `Contract Client ${suffix}`,
      bookedByEmail: `contract-client-${suffix}@example.com`,
      ttlSeconds: 600,
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    hold: { id: string; expiresAt: string; startAt: string; endAt: string };
  };
}

async function startBooking(
  request: import("@playwright/test").APIRequestContext,
  offerId: string,
  holdId: string,
  suffix: string
) {
  const response = await request.post(`${API_URL}/coaching/public/offers/${offerId}/bookings`, {
    data: {
      holdId,
      locale: "en",
      client: {
        displayName: `Contract Client ${suffix}`,
        email: `contract-client-${suffix}@example.com`,
      },
    },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    engagement: { id: string; status: string; paymentStatus: string; contractStatus?: string };
    session: { id: string };
    payment: {
      id: string;
      status: string;
      providerCheckoutSessionId: string | null;
      providerCheckoutUrl: string | null;
    };
    checkoutUrl: string;
  };
}

async function getEngagementDetail(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  engagementId: string
) {
  const response = await request.get(`${API_URL}/coaching-engagements/${engagementId}`, {
    headers: auth,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as {
    engagement: {
      id: string;
      clientPartyId: string;
      locale: string;
      status: string;
      paymentStatus: string;
      contractStatus: string;
      signedContractDocumentId?: string | null;
    };
    contractRequest: {
      id: string;
      status: string;
      templateLocale: string;
      contractTitle: string;
      recipientName?: string | null;
      recipientEmail?: string | null;
      signerName?: string | null;
      signerEmail?: string | null;
      requestedAt: string;
      deliveredAt?: string | null;
      viewedAt?: string | null;
      completedAt?: string | null;
      draftDocumentId: string;
      signedDocumentId?: string | null;
    } | null;
    sessions: Array<{ id: string; status: string; startAt: string; endAt: string }>;
    payments: Array<{
      id: string;
      status: string;
      provider: string;
      providerCheckoutSessionId: string | null;
      providerPaymentRef: string | null;
    }>;
    artifacts: Array<{ id: string; title: string; kind: string }>;
    timeline: Array<{ eventType: string; metadata?: Record<string, unknown> }>;
  };
}

async function postStripeWebhook(
  request: import("@playwright/test").APIRequestContext,
  event: Record<string, unknown>
) {
  const rawBody = JSON.stringify(event);
  const fakeSignature = signFakeStripeWebhook(rawBody, "test-coaching-webhook-secret");
  let response = await request.post(`${API_URL}/coaching-engagements/webhooks/stripe`, {
    headers: {
      "Content-Type": "application/json",
      "stripe-signature": fakeSignature,
    },
    data: rawBody,
  });
  if (response.ok()) {
    return;
  }

  const stripeSecret =
    process.env.STRIPE_WEBHOOK_SECRET ??
    "whsec_cd7d117e34d198633d3c215ce9321c687c821577f783047cff8ecf25f0edeee5";
  const stripeSignature = Stripe.webhooks.generateTestHeaderString({
    payload: rawBody,
    secret: stripeSecret,
  });
  response = await request.post(`${API_URL}/coaching-engagements/webhooks/stripe`, {
    headers: {
      "Content-Type": "application/json",
      "stripe-signature": stripeSignature,
    },
    data: rawBody,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
}

async function runOutboxTick(request: import("@playwright/test").APIRequestContext) {
  const serviceToken = process.env.WORKER_API_SERVICE_TOKEN?.trim();
  const legacyWorkerKey = process.env.INTERNAL_WORKER_KEY?.trim();
  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (serviceToken) {
    headers["x-service-token"] = serviceToken;
  } else if (legacyWorkerKey) {
    headers["x-worker-key"] = legacyWorkerKey;
  }

  const response = await request.post(`${API_URL}/internal/background/outbox/run`, {
    headers,
    data: { limit: 50 },
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  return (await response.json()) as { processedCount: number };
}

async function waitForContractRequest(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  engagementId: string
) {
  const deadline = Date.now() + 45_000;
  while (Date.now() < deadline) {
    await runOutboxTick(request);
    const detail = await getEngagementDetail(request, auth, engagementId);
    if (detail.contractRequest) {
      return detail;
    }
    await sleep(1_000);
  }
  throw new Error("Timed out waiting for coaching contract request");
}

async function downloadDocumentText(
  request: import("@playwright/test").APIRequestContext,
  auth: ReturnType<typeof buildAuthHeaders>,
  documentId: string
) {
  const response = await request.get(`${API_URL}/documents/${documentId}/download`, {
    headers: auth,
  });
  expect(response.ok(), await response.text()).toBeTruthy();
  const bytes = await response.body();
  return Buffer.from(bytes).toString("utf8");
}

async function listContractRequests(tenantId: string, engagementId: string) {
  const body = await apiClient.post<{
    contractRequests: Array<{
      id: string;
      engagementId: string;
      clientPartyId: string;
      provider: string;
      status: string;
      requestToken: string;
      requestTokenHash: string;
      templateLocale: string;
      contractTitle: string;
      contractBody: string;
      recipientName: string | null;
      recipientEmail: string | null;
      signerName: string | null;
      signerEmail: string | null;
      requestedAt: string;
      deliveredAt: string | null;
      viewedAt: string | null;
      completedAt: string | null;
      draftDocumentId: string;
      signedDocumentId: string | null;
    }>;
  }>("/test/coaching/contract-requests", {
    tenantId,
    engagementId,
  });
  return body.contractRequests;
}

test.describe("Coaching contract signature", () => {
  test("uses the right contract template, binds the request to the booking, sends one signature request, and waits for signature before confirmation", async ({
    page,
    request,
    testData,
  }, testInfo) => {
    const screenshotDir = screenshotDirFor(testInfo);
    const suffix = uniqueSuffix();
    const auth = await loginAsSeededUser(request, testData);
    const headers = buildAuthHeaders(auth);
    const offerTimezone = "America/New_York";
    const viewerTimezone = "Europe/Berlin";
    const clientEmail = `contract-client-${suffix}@example.com`;
    const signerName = `Contract Signer ${suffix}`;

    const offer = await createOffer(request, headers, offerTimezone, suffix);
    const contractTemplate = offer.contractTemplate?.en;
    expect(contractTemplate).toContain(`Coaching agreement for ${suffix}`);

    const localMonday = nextLocalWeekday(1, offerTimezone, 8);
    const rangeStart = fromZonedTime(`${localMonday}T00:00:00`, offerTimezone).toISOString();
    const rangeEnd = fromZonedTime(
      `${plusLocalDays(localMonday, 1)}T00:00:00`,
      offerTimezone
    ).toISOString();
    const availability = await getAvailability(request, offer.id, {
      from: rangeStart,
      to: rangeEnd,
      timezone: viewerTimezone,
    });
    expect(availability.slots).toHaveLength(3);

    const hold = await createHold(request, offer.id, availability.slots[0], suffix);
    const booking = await startBooking(request, offer.id, hold.hold.id, suffix);
    expect(booking.engagement.status).toBe("pending_payment");
    expect(booking.engagement.paymentStatus).toBe("pending");

    let detail = await waitForContractRequest(request, headers, booking.engagement.id);
    expect(detail.engagement.status).toBe("pending_payment");
    expect(detail.engagement.contractStatus).toBe("pending");
    expect(detail.contractRequest).not.toBeNull();
    expect(detail.contractRequest?.recipientEmail).toBe(clientEmail);
    expect(detail.contractRequest?.recipientName).toBe(`Contract Client ${suffix}`);
    expect(detail.contractRequest?.templateLocale).toBe("en");
    expect(detail.contractRequest?.contractTitle).toBe(offer.title.en);
    expect(
      detail.timeline.filter((entry) => entry.eventType === "coaching.contract_signature.requested")
    ).toHaveLength(1);

    const initialContractRequestId = detail.contractRequest!.id;
    await runOutboxTick(request);
    detail = await getEngagementDetail(request, headers, booking.engagement.id);
    expect(detail.contractRequest?.id).toBe(initialContractRequestId);
    expect(
      detail.timeline.filter((entry) => entry.eventType === "coaching.contract_signature.requested")
    ).toHaveLength(1);

    const contractRequests = await listContractRequests(testData.tenant.id, booking.engagement.id);
    expect(contractRequests).toHaveLength(1);
    expect(contractRequests[0]?.id).toBe(initialContractRequestId);
    expect(contractRequests[0]?.engagementId).toBe(booking.engagement.id);
    expect(contractRequests[0]?.clientPartyId).toBe(detail.engagement.clientPartyId);
    expect(contractRequests[0]?.recipientEmail).toBe(clientEmail);
    expect(contractRequests[0]?.contractBody).toBe(contractTemplate);

    const draftDocumentText = await downloadDocumentText(
      request,
      headers,
      detail.contractRequest!.draftDocumentId
    );
    expect(draftDocumentText).toContain(`Engagement: ${booking.engagement.id}`);
    expect(draftDocumentText).toContain(`Client party: ${detail.engagement.clientPartyId}`);
    for (const line of contractTemplate!.split("\n")) {
      expect(draftDocumentText).toContain(line);
    }

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "01-contract-request-created",
      "Contract request created",
      {
        engagement: detail.engagement,
        contractRequest: detail.contractRequest,
        timeline: detail.timeline,
        draftDocumentSnippet: draftDocumentText.slice(0, 500),
      }
    );

    const publicContractUrl = `${API_URL}/coaching/public/contracts/${booking.engagement.id}/${contractRequests[0]!.requestToken}`;
    await page.goto(publicContractUrl, { waitUntil: "networkidle" });
    await expect(page.locator("h1")).toContainText(offer.title.en);
    await expect(page.locator("pre")).toContainText(`Coaching agreement for ${suffix}`);

    const publicPagePath = join(screenshotDir, "02-public-contract-page.png");
    await page.screenshot({ path: publicPagePath, fullPage: true });
    await testInfo.attach("02-public-contract-page", {
      path: publicPagePath,
      contentType: "image/png",
    });

    detail = await getEngagementDetail(request, headers, booking.engagement.id);
    expect(detail.contractRequest?.status).toBe("viewed");
    expect(detail.contractRequest?.viewedAt).toBeTruthy();

    const successEvent = {
      id: `evt_contract_success_${suffix}`,
      type: "checkout.session.completed",
      data: {
        object: {
          id: booking.payment.providerCheckoutSessionId,
          object: "checkout.session",
          payment_intent: `pi_contract_success_${suffix}`,
          metadata: {
            tenantId: testData.tenant.id,
            engagementId: booking.engagement.id,
            paymentId: booking.payment.id,
          },
        },
      },
    };
    await postStripeWebhook(request, successEvent);

    detail = await getEngagementDetail(request, headers, booking.engagement.id);
    expect(detail.engagement.paymentStatus).toBe("captured");
    expect(detail.engagement.contractStatus).toBe("pending");
    expect(detail.engagement.status).toBe("pending_signature");
    expect(detail.payments[0]?.status).toBe("captured");
    expect(
      detail.timeline.filter((entry) => entry.eventType === "coaching.payment.captured")
    ).toHaveLength(1);

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "03-payment-captured-awaiting-signature",
      "Payment captured but still awaiting signature",
      {
        engagement: detail.engagement,
        contractRequest: detail.contractRequest,
        payments: detail.payments,
        timeline: detail.timeline,
      }
    );

    await page.goto(publicContractUrl, { waitUntil: "networkidle" });
    await page.locator('input[name="signerName"]').fill(signerName);
    await page.locator('input[name="signerEmail"]').fill(clientEmail);
    await page.getByRole("button", { name: "Sign agreement" }).click();
    await expect(page.locator("#status")).toHaveText("Agreement signed. You can close this page.");

    const signedPagePath = join(screenshotDir, "04-contract-signed-page.png");
    await page.screenshot({ path: signedPagePath, fullPage: true });
    await testInfo.attach("04-contract-signed-page", {
      path: signedPagePath,
      contentType: "image/png",
    });

    detail = await getEngagementDetail(request, headers, booking.engagement.id);
    expect(detail.engagement.contractStatus).toBe("signed");
    expect(detail.engagement.status).toBe("ready");
    expect(detail.contractRequest?.status).toBe("signed");
    expect(detail.contractRequest?.completedAt).toBeTruthy();
    expect(detail.contractRequest?.signerName).toBe(signerName);
    expect(detail.contractRequest?.signerEmail).toBe(clientEmail);
    expect(detail.contractRequest?.signedDocumentId).toBeTruthy();
    expect(
      detail.timeline.filter((entry) => entry.eventType === "coaching.contract.signed")
    ).toHaveLength(1);

    const signedDocumentText = await downloadDocumentText(
      request,
      headers,
      detail.contractRequest!.signedDocumentId!
    );
    expect(signedDocumentText).toContain(`Engagement: ${booking.engagement.id}`);
    expect(signedDocumentText).toContain(`Client party: ${detail.engagement.clientPartyId}`);
    expect(signedDocumentText).toContain(`Signer: ${signerName}`);
    expect(signedDocumentText).toContain(`Signer email: ${clientEmail}`);
    for (const line of contractTemplate!.split("\n")) {
      expect(signedDocumentText).toContain(line);
    }

    const finalContractRequests = await listContractRequests(
      testData.tenant.id,
      booking.engagement.id
    );
    expect(finalContractRequests).toHaveLength(1);
    expect(finalContractRequests[0]?.status).toBe("signed");
    expect(finalContractRequests[0]?.signerName).toBe(signerName);
    expect(finalContractRequests[0]?.signedDocumentId).toBe(
      detail.contractRequest?.signedDocumentId ?? null
    );

    await captureState(
      page,
      testInfo,
      screenshotDir,
      "05-final-contract-state",
      "Final contract state",
      {
        engagement: detail.engagement,
        contractRequest: detail.contractRequest,
        timeline: detail.timeline,
        signedDocumentSnippet: signedDocumentText.slice(0, 500),
      }
    );

    console.log(`Coaching contract signature screenshots saved to ${screenshotDir}`);
  });
});
